title: EVALab Documentation
description: Documentation Page for EVALab Members
theme: just-the-docs

url: https://chipeval.github.io/docs

nav:
  - title: "New comer training program"
    url: /
    
  - title: "Seminar"
    children:
      - title: "250910"
        url: /seminar/250910
